;;; emacs-batteries-test.el --- Tests for emacs-batteries -*- lexical-binding: t; -*-

;;; Code:

(require 'cl-lib)
(require 'ert)
(require 'autorevert)
(require 'delsel)
(require 'electric)
(require 'mb-depth)
(require 'paren)
(require 'pixel-scroll)
(require 'recentf)
(require 'repeat)
(require 'savehist)
(require 'saveplace)
(require 'so-long)
(require 'ffap)
(require 'isearch)
(require 'uniquify)
(require 'winner)
(require 'which-key)
(require 'xref)
(require 'apropos)
(require 'dired)
(require 'dired-aux)
(require 'ediff)
(require 'bookmark)
(require 'vc-git)
(require 'compile)
(require 'editorconfig)
(require 'imenu)
(require 'epg)
(require 'gnutls)
(require 'subword)
(require 'display-line-numbers)
(require 'cursor-sensor)
(require 'cus-edit)
(require 'comint)
(require 'tramp)
(require 'diff-mode)
(require 'esh-mode)
(require 'url)
(require 'emacs-batteries)

(defvar emacs-batteries-bootstrap-cache-file)
(defvar emacs-batteries-bootstrap-remote-url)
(defvar emacs-batteries-bootstrap-refresh-interval)
(defvar emacs-batteries-bootstrap-checksum)
(defvar emacs-batteries-bootstrap-checksum-algorithm)
(defvar emacs-batteries--saved-file-name-handler-alist nil)
(defvar global-so-long-mode)
(defvar helper-loaded)
(defvar auto-save-no-message)
(defvar find-file-visit-truename)
(defvar vc-follow-symlinks)
(defvar bookmark-save-flag)
(defvar dired-dwim-target)
(defvar dired-recursive-copies)
(defvar dired-recursive-deletes)
(defvar dired-create-destination-dirs)
(defvar dired-kill-when-opening-new-dired-buffer)
(defvar dired-listing-switches)
(defvar dired-auto-revert-buffer)
(defvar dired-vc-rename-file)
(defvar ediff-window-setup-function)
(defvar ediff-split-window-function)
(defvar show-paren-when-point-inside-paren)
(defvar show-paren-when-point-in-periphery)
(defvar show-paren-delay)
(defvar xref-show-definitions-function)
(defvar apropos-do-all)
(defvar set-mark-command-repeat-pop)
(defvar window-resize-pixelwise)
(defvar mouse-yank-at-point)
(defvar auto-window-vscroll)
(defvar inhibit-compacting-font-caches)
(defvar frame-resize-pixelwise)
(defvar bidi-inhibit-bpa)
(defvar scroll-conservatively)
(defvar scroll-error-top-bottom)
(defvar hscroll-margin)
(defvar hscroll-step)
(defvar vc-git-print-log-follow)
(defvar eval-expression-print-length)
(defvar eval-expression-print-level)
(defvar compilation-scroll-output)
(defvar compilation-always-kill)
(defvar compilation-ask-about-save)
(defvar save-abbrevs)
(defvar select-enable-clipboard)
(defvar interprogram-cut-function)
(defvar interprogram-paste-function)
(defvar gnutls-verify-error)
(defvar gnutls-min-prime-bits)
(defvar imenu-auto-rescan)
(defvar resize-mini-windows)
(defvar comment-multi-line)
(defvar comment-empty-lines)
(defvar truncate-string-ellipsis)
(defvar completions-sort)
(defvar initial-scratch-message)
(defvar initial-major-mode)
(defvar jit-lock-defer-time)
(defvar process-adaptive-read-buffering)
(defvar global-text-scale-adjust-resizes-frames)
(defvar display-time-default-load-average)
(defvar epg-pinentry-mode)
(defvar next-line-add-newlines)
(defvar kill-buffer-delete-auto-save-files)
(defvar auto-save-include-big-deletions)
(defvar find-file-suppress-same-file-warnings)
(defvar confirm-nonexistent-file-or-buffer)
(defvar lazy-highlight-initial-delay)
(defvar tab-first-completion)
(defvar editorconfig-mode)
(defvar custom-file)
(defvar minibuffer-setup-hook)
(defvar after-save-hook)
(defvar grep-use-headings)
(defvar project-mode-line)
(defvar describe-bindings-outline)
(defvar diff-refine)
(defvar kill-ring-deindent-mode)
(defvar remote-file-name-inhibit-delete-by-moving-to-trash)
(defvar remote-file-name-inhibit-auto-save)
(defvar vc-git-diff-switches)
(defvar blink-matching-paren)
(defvar custom-buffer-done-kill)
(defvar dired-movement-style)
(defvar dired-deletion-confirmer)
(defvar comint-prompt-read-only)
(defvar eshell-history-append)
(defvar imenu-flatten)
(defvar text-mode-ispell-word-completion)
(defvar savehist-additional-variables)
(defvar undo-limit)
(defvar undo-strong-limit)
(defvar split-width-threshold)
(defvar tramp-verbose)
(defvar visual-wrap-prefix-mode)
(defvar completion-preview-mode)
(defvar completions-header-format)
(defvar what-cursor-show-names)
(defvar large-file-warning-threshold)
(defvar eldoc-echo-area-use-multiline-p)
(defvar mouse-wheel-tilt-scroll)
(defvar proced-enable-color-flag)
(defvar prog-mode-hook)
(defvar use-file-dialog)
(defvar backup-by-copying-when-linked)
(defvar display-raw-bytes-as-hex)
(defvar help-enable-variable-value-editing)
(defvar compilation-max-output-line-length)
(defvar register-use-preview)
(defvar help-window-keep-selected)
(defvar tab-bar-show)
(defvar read-minibuffer-restore-windows)
(defvar switch-to-buffer-in-dedicated-window)
(defvar url-privacy-level)
(defvar isearch-allow-scroll)
(defvar isearch-wrap-pause)
(defvar lazy-highlight-buffer)
(defvar shell-kill-buffer-on-exit)
(defvar comint-scroll-to-bottom-on-input)
(defvar native-compile-prune-cache)
(defvar xref-history-storage)
(defvar find-library-include-other-files)
(defvar outline-minor-mode-cycle)
(defvar ediff-keep-variants)
(defvar native-comp-async-report-warnings-errors)
(defvar x-underline-at-descent-line)
(defvar emacs-batteries--interprogram-cut-base-function)
(defvar emacs-batteries--interprogram-paste-base-function)
(defvar emacs-batteries--last-macos-file-clipboard-paste)
(defvar emacs-batteries--last-macos-terminal-clipboard-paste)
(defvar emacs-batteries--last-interprogram-cut-text)

(defconst emacs-batteries-test--baseline-values
  `((history-length . ,history-length)
    (history-delete-duplicates . ,history-delete-duplicates)
    (savehist-file . ,savehist-file)
    (savehist-autosave-interval . ,savehist-autosave-interval)
    (save-place-file . ,save-place-file)
    (recentf-save-file . ,recentf-save-file)
    (recentf-max-saved-items . ,recentf-max-saved-items)
    (enable-recursive-minibuffers . ,enable-recursive-minibuffers)
    (confirm-kill-emacs . ,confirm-kill-emacs)
    (read-extended-command-predicate
     . ,read-extended-command-predicate)
    (selection-coding-system . ,selection-coding-system)
    (buffer-file-coding-system . ,buffer-file-coding-system)
    (tab-always-indent . ,tab-always-indent)
    (tab-first-completion . ,tab-first-completion)
    (completion-cycle-threshold . ,completion-cycle-threshold)
    (switch-to-buffer-obey-display-actions
     . ,switch-to-buffer-obey-display-actions)
    (help-window-select . ,help-window-select)
    (blink-cursor-mode . ,blink-cursor-mode)
    (cursor-in-non-selected-windows . ,cursor-in-non-selected-windows)
    (vc-handled-backends . ,(copy-tree vc-handled-backends))
    (vc-git-print-log-follow . ,vc-git-print-log-follow)
    (read-process-output-max . ,read-process-output-max)
    (inhibit-default-init . ,inhibit-default-init)
    (inhibit-startup-screen . ,inhibit-startup-screen)
    (default-frame-alist . ,(copy-tree default-frame-alist))
    (initial-frame-alist . ,(copy-tree initial-frame-alist))
    (frame-inhibit-implied-resize . ,frame-inhibit-implied-resize)
    (file-name-handler-alist . ,(copy-tree file-name-handler-alist))
    (fast-but-imprecise-scrolling . ,fast-but-imprecise-scrolling)
    (redisplay-skip-fontification-on-input
     . ,redisplay-skip-fontification-on-input)
    (global-so-long-mode . ,global-so-long-mode)
    (recentf-mode . ,recentf-mode)
    (global-auto-revert-mode . ,global-auto-revert-mode)
    (global-auto-revert-non-file-buffers
     . ,global-auto-revert-non-file-buffers)
    (pixel-scroll-precision-mode . ,pixel-scroll-precision-mode)
    (delete-selection-mode . ,delete-selection-mode)
    (repeat-mode . ,repeat-mode)
    (show-paren-mode . ,show-paren-mode)
    (show-paren-delay . ,show-paren-delay)
    (winner-mode . ,winner-mode)
    (minibuffer-depth-indicate-mode . ,minibuffer-depth-indicate-mode)
    (minibuffer-electric-default-mode
     . ,minibuffer-electric-default-mode)
    (use-dialog-box . ,use-dialog-box)
    (use-short-answers . ,use-short-answers)
    (ring-bell-function . ,ring-bell-function)
    (gc-cons-threshold . ,gc-cons-threshold)
    (gc-cons-percentage . ,gc-cons-percentage)
    (emacs-startup-hook . ,(copy-tree emacs-startup-hook))
    (after-change-major-mode-hook
     . ,(copy-tree after-change-major-mode-hook))
    (minibuffer-setup-hook . ,(copy-tree minibuffer-setup-hook))
    (after-save-hook . ,(copy-tree after-save-hook))
    (emacs-batteries--saved-gc-cons-threshold
     . ,emacs-batteries--saved-gc-cons-threshold)
    (emacs-batteries--saved-gc-cons-percentage
     . ,emacs-batteries--saved-gc-cons-percentage)
    (emacs-batteries--saved-file-name-handler-alist
     . ,(copy-tree emacs-batteries--saved-file-name-handler-alist))
    (locale-coding-system . ,locale-coding-system)
    (default-process-coding-system . ,default-process-coding-system)
    (file-name-coding-system . ,file-name-coding-system)
    (default-file-name-coding-system . ,default-file-name-coding-system)
    (make-backup-files . ,make-backup-files)
    (backup-by-copying . ,backup-by-copying)
    (delete-by-moving-to-trash . ,delete-by-moving-to-trash)
    (kill-whole-line . ,kill-whole-line)
    (read-buffer-completion-ignore-case
     . ,read-buffer-completion-ignore-case)
    (completion-ignore-case . ,completion-ignore-case)
    (version-control . ,version-control)
    (delete-old-versions . ,delete-old-versions)
    (kept-new-versions . ,kept-new-versions)
    (kept-old-versions . ,kept-old-versions)
    (kill-do-not-save-duplicates . ,kill-do-not-save-duplicates)
    (select-enable-clipboard . ,select-enable-clipboard)
    (interprogram-cut-function . ,interprogram-cut-function)
    (interprogram-paste-function . ,interprogram-paste-function)
    (save-interprogram-paste-before-kill
     . ,save-interprogram-paste-before-kill)
    (tty-setup-hook . ,(copy-tree tty-setup-hook))
    (create-lockfiles . ,create-lockfiles)
    (backup-directory-alist . ,(copy-tree backup-directory-alist))
    (auto-save-default . ,auto-save-default)
    (auto-save-file-name-transforms . ,(copy-tree auto-save-file-name-transforms))
    (auto-save-list-file-prefix . ,auto-save-list-file-prefix)
    (load-prefer-newer . ,load-prefer-newer)
    (scroll-preserve-screen-position . ,scroll-preserve-screen-position)
    (column-number-mode . ,column-number-mode)
    (uniquify-buffer-name-style . ,uniquify-buffer-name-style)
    (isearch-lazy-count . ,isearch-lazy-count)
    (lazy-count-prefix-format . ,lazy-count-prefix-format)
    (lazy-count-suffix-format . ,lazy-count-suffix-format)
    (lazy-highlight-initial-delay . ,lazy-highlight-initial-delay)
    (read-file-name-completion-ignore-case
     . ,read-file-name-completion-ignore-case)
    (completions-detailed . ,completions-detailed)
    (require-final-newline . ,require-final-newline)
    (ffap-machine-p-known . ,ffap-machine-p-known)
    (sentence-end-double-space . ,sentence-end-double-space)
    (set-mark-command-repeat-pop . ,set-mark-command-repeat-pop)
    (window-resize-pixelwise . ,window-resize-pixelwise)
    (show-paren-when-point-inside-paren . ,show-paren-when-point-inside-paren)
    (show-paren-when-point-in-periphery . ,show-paren-when-point-in-periphery)
    (which-key-mode . ,which-key-mode)
    (context-menu-mode . ,context-menu-mode)
    (xref-show-definitions-function . ,xref-show-definitions-function)
    (apropos-do-all . ,apropos-do-all)
    (dired-dwim-target . ,dired-dwim-target)
    (dired-recursive-copies . ,dired-recursive-copies)
    (dired-recursive-deletes . ,dired-recursive-deletes)
    (dired-create-destination-dirs . ,dired-create-destination-dirs)
    (dired-kill-when-opening-new-dired-buffer . ,dired-kill-when-opening-new-dired-buffer)
    (dired-listing-switches . ,dired-listing-switches)
    (dired-auto-revert-buffer . ,dired-auto-revert-buffer)
    (ediff-window-setup-function . ,ediff-window-setup-function)
    (ediff-split-window-function . ,ediff-split-window-function)
    (auto-save-no-message . ,auto-save-no-message)
    (auto-save-include-big-deletions . ,auto-save-include-big-deletions)
    (find-file-visit-truename . ,find-file-visit-truename)
    (find-file-suppress-same-file-warnings . ,find-file-suppress-same-file-warnings)
    (confirm-nonexistent-file-or-buffer . ,confirm-nonexistent-file-or-buffer)
    (vc-follow-symlinks . ,vc-follow-symlinks)
    (bookmark-save-flag . ,bookmark-save-flag)
    (save-abbrevs . ,save-abbrevs)
    (kill-buffer-delete-auto-save-files . ,kill-buffer-delete-auto-save-files)
    (mouse-yank-at-point . ,mouse-yank-at-point)
    (auto-window-vscroll . ,auto-window-vscroll)
    (inhibit-compacting-font-caches . ,inhibit-compacting-font-caches)
    (frame-resize-pixelwise . ,frame-resize-pixelwise)
    (bidi-inhibit-bpa . ,bidi-inhibit-bpa)
    (scroll-conservatively . ,scroll-conservatively)
    (scroll-error-top-bottom . ,scroll-error-top-bottom)
    (hscroll-margin . ,hscroll-margin)
    (hscroll-step . ,hscroll-step)
    (jit-lock-defer-time . ,jit-lock-defer-time)
    (process-adaptive-read-buffering . ,process-adaptive-read-buffering)
    (next-line-add-newlines . ,next-line-add-newlines)
    (eval-expression-print-length . ,eval-expression-print-length)
    (eval-expression-print-level . ,eval-expression-print-level)
    (compilation-scroll-output . ,compilation-scroll-output)
    (compilation-always-kill . ,compilation-always-kill)
    (compilation-ask-about-save . ,compilation-ask-about-save)
    (gnutls-verify-error . ,gnutls-verify-error)
    (gnutls-min-prime-bits . ,gnutls-min-prime-bits)
    (epg-pinentry-mode . ,epg-pinentry-mode)
    (imenu-auto-rescan . ,imenu-auto-rescan)
    (resize-mini-windows . ,resize-mini-windows)
    (comment-multi-line . ,comment-multi-line)
    (comment-empty-lines . ,comment-empty-lines)
    (truncate-string-ellipsis . ,truncate-string-ellipsis)
    (initial-scratch-message . ,initial-scratch-message)
    (initial-major-mode . ,initial-major-mode)
    (editorconfig-mode . ,editorconfig-mode)
    (custom-file . ,custom-file)
    (minibuffer-prompt-properties . ,(copy-tree minibuffer-prompt-properties))
    (vc-git-diff-switches . ,(and (boundp 'vc-git-diff-switches) vc-git-diff-switches))
    (blink-matching-paren . ,blink-matching-paren)
    (custom-buffer-done-kill . ,custom-buffer-done-kill)
    (dired-deletion-confirmer . ,dired-deletion-confirmer)
    (comint-prompt-read-only . ,comint-prompt-read-only)
    (undo-limit . ,undo-limit)
    (undo-strong-limit . ,undo-strong-limit)
    (split-width-threshold . ,split-width-threshold)
    (tramp-verbose . ,tramp-verbose)
    (diff-refine . ,diff-refine)
    (savehist-additional-variables . ,(copy-tree savehist-additional-variables))
    (large-file-warning-threshold . ,large-file-warning-threshold)
    (eldoc-echo-area-use-multiline-p . ,eldoc-echo-area-use-multiline-p)
    (mouse-wheel-tilt-scroll . ,mouse-wheel-tilt-scroll)
    (prog-mode-hook . ,(copy-tree prog-mode-hook))
    (use-file-dialog . ,use-file-dialog)
    (backup-by-copying-when-linked . ,backup-by-copying-when-linked)
    (display-raw-bytes-as-hex . ,display-raw-bytes-as-hex)
    (url-privacy-level . ,url-privacy-level)
    (isearch-allow-scroll . ,isearch-allow-scroll)
    (comint-scroll-to-bottom-on-input . ,comint-scroll-to-bottom-on-input)
    (ediff-keep-variants . ,ediff-keep-variants)
    (display-time-default-load-average
     . ,(and (boundp 'display-time-default-load-average) display-time-default-load-average))
    (xref-history-storage . ,(and (boundp 'xref-history-storage) xref-history-storage))
    (find-library-include-other-files
     . ,(and (boundp 'find-library-include-other-files) find-library-include-other-files))
    (isearch-wrap-pause . ,(and (boundp 'isearch-wrap-pause) isearch-wrap-pause))
    (lazy-highlight-buffer . ,(and (boundp 'lazy-highlight-buffer) lazy-highlight-buffer))
    (grep-use-headings . ,(and (boundp 'grep-use-headings) grep-use-headings))
    (dired-movement-style . ,(and (boundp 'dired-movement-style) dired-movement-style))
    (dired-vc-rename-file . ,(and (boundp 'dired-vc-rename-file) dired-vc-rename-file))
    (eshell-history-append . ,(and (boundp 'eshell-history-append) eshell-history-append))
    (shell-kill-buffer-on-exit . ,(and (boundp 'shell-kill-buffer-on-exit) shell-kill-buffer-on-exit))
    (compilation-max-output-line-length
     . ,(and (boundp 'compilation-max-output-line-length) compilation-max-output-line-length))
    (help-window-keep-selected
     . ,(and (boundp 'help-window-keep-selected) help-window-keep-selected))
    (switch-to-buffer-in-dedicated-window
     . ,(and (boundp 'switch-to-buffer-in-dedicated-window) switch-to-buffer-in-dedicated-window))
    (what-cursor-show-names . ,(and (boundp 'what-cursor-show-names) what-cursor-show-names))
    (completions-header-format
     . ,(and (boundp 'completions-header-format) completions-header-format))
    (help-enable-variable-value-editing
     . ,(and (boundp 'help-enable-variable-value-editing) help-enable-variable-value-editing))
    (register-use-preview . ,(and (boundp 'register-use-preview) register-use-preview))
    (tab-bar-show . ,(and (boundp 'tab-bar-show) tab-bar-show))
    (outline-minor-mode-cycle
     . ,(and (boundp 'outline-minor-mode-cycle) outline-minor-mode-cycle))
    (project-mode-line . ,(and (boundp 'project-mode-line) project-mode-line))
    (describe-bindings-outline
     . ,(and (boundp 'describe-bindings-outline) describe-bindings-outline))
    (imenu-flatten . ,(and (boundp 'imenu-flatten) imenu-flatten))
    (native-compile-prune-cache
     . ,(and (boundp 'native-compile-prune-cache) native-compile-prune-cache))
    (native-comp-async-report-warnings-errors
     . ,(and (boundp 'native-comp-async-report-warnings-errors)
             native-comp-async-report-warnings-errors))
    (emacs-batteries--interprogram-cut-base-function
     . ,emacs-batteries--interprogram-cut-base-function)
    (emacs-batteries--interprogram-paste-base-function
     . ,emacs-batteries--interprogram-paste-base-function)
    (emacs-batteries--last-macos-file-clipboard-paste
     . ,emacs-batteries--last-macos-file-clipboard-paste)
    (emacs-batteries--last-macos-terminal-clipboard-paste
     . ,emacs-batteries--last-macos-terminal-clipboard-paste)
    (emacs-batteries--last-interprogram-cut-text
     . ,emacs-batteries--last-interprogram-cut-text)
    (global-text-scale-adjust-resizes-frames
     . ,(and (boundp 'global-text-scale-adjust-resizes-frames)
             global-text-scale-adjust-resizes-frames))
    (proced-enable-color-flag
     . ,(and (boundp 'proced-enable-color-flag) proced-enable-color-flag))
    (read-minibuffer-restore-windows
     . ,(and (boundp 'read-minibuffer-restore-windows) read-minibuffer-restore-windows))
    (text-mode-ispell-word-completion
     . ,(and (boundp 'text-mode-ispell-word-completion) text-mode-ispell-word-completion))
    (completions-sort . ,(and (boundp 'completions-sort) completions-sort)))
  "Baseline values captured before tests mutate global state.")

(defun emacs-batteries-test--disable-managed-modes ()
  "Disable all modes managed by `emacs-batteries-setup'."
  (dolist (mode '(savehist-mode save-place-mode recentf-mode
                  global-auto-revert-mode global-so-long-mode
                  winner-mode pixel-scroll-precision-mode
                  delete-selection-mode repeat-mode show-paren-mode
                  minibuffer-depth-indicate-mode
                  minibuffer-electric-default-mode
                  column-number-mode
                  which-key-mode context-menu-mode
                  editorconfig-mode))
    (when (symbol-value mode)
      (funcall mode -1)))
  (when (and (fboundp 'global-visual-wrap-prefix-mode)
             (boundp 'visual-wrap-prefix-mode)
             (bound-and-true-p global-visual-wrap-prefix-mode))
    (global-visual-wrap-prefix-mode -1))
  (when (and (fboundp 'global-kill-ring-deindent-mode)
             (boundp 'kill-ring-deindent-mode)
             (bound-and-true-p global-kill-ring-deindent-mode))
    (global-kill-ring-deindent-mode -1))
  (when (timerp savehist-timer)
    (cancel-timer savehist-timer)
    (setq savehist-timer nil)))

(defun emacs-batteries-test--flush-deferred ()
  "Run any deferred setup functions immediately."
  (when (fboundp 'emacs-batteries--run-deferred)
    (emacs-batteries--run-deferred)))

(defmacro emacs-batteries-test--with-sandbox (&rest body)
  "Run BODY with isolated state for `emacs-batteries'."
  (declare (indent 0) (debug t))
  `(let* ((temp-directory (make-temp-file "emacs-batteries-" t))
          (emacs-batteries-state-directory
           (expand-file-name "state/" temp-directory))
          (emacs-batteries-custom-file nil))
     (unwind-protect
         (progn
           (emacs-batteries-test--disable-managed-modes)
           (setq emacs-batteries--deferred-functions nil)
           (dolist (cell emacs-batteries-test--baseline-values)
             (set (car cell) (copy-tree (cdr cell))))
           ,@body)
       (emacs-batteries-test--disable-managed-modes)
       (setq emacs-batteries--deferred-functions nil)
       (delete-directory temp-directory t))))

(defun emacs-batteries-test--fixture-path (path)
  "Expand PATH relative to the repository root."
  (expand-file-name path default-directory))

(defun emacs-batteries-test--emacs-program ()
  "Return the current Emacs executable path."
  (if invocation-directory
      (expand-file-name invocation-name invocation-directory)
    invocation-name))

(defun emacs-batteries-test--call-emacs (&rest args)
  "Run a child Emacs with ARGS and return its exit code and output."
  (with-temp-buffer
    (let ((exit-code
           (apply #'process-file
                  (emacs-batteries-test--emacs-program)
                  nil
                  (current-buffer)
                  nil
                  args)))
      (cons exit-code (buffer-string)))))

(ert-deftest emacs-batteries-setup-enables-defaults ()
  (emacs-batteries-test--with-sandbox
    (emacs-batteries-setup)
    (should savehist-mode)
    (should save-place-mode)
    (should recentf-mode)
    (should (= recentf-max-saved-items
               emacs-batteries-recentf-max-saved-items))
    (should global-auto-revert-mode)
    (should global-auto-revert-non-file-buffers)
    (should enable-recursive-minibuffers)
    (should (eq confirm-kill-emacs emacs-batteries-confirm-kill-emacs))
    (should (eq read-extended-command-predicate
                emacs-batteries-read-extended-command-predicate))
    (should (eq history-delete-duplicates t))
    (should (= history-length emacs-batteries-history-length))
    (should (eq savehist-autosave-interval nil))
    (should global-so-long-mode)
    (should winner-mode)
    (should minibuffer-depth-indicate-mode)
    (should minibuffer-electric-default-mode)
    (should pixel-scroll-precision-mode)
    (should fast-but-imprecise-scrolling)
    (should redisplay-skip-fontification-on-input)
    (should (equal vc-handled-backends '(Git)))
    (should vc-git-print-log-follow)
    (should-not cursor-in-non-selected-windows)
    (should-not blink-cursor-mode)
    (should kill-whole-line)
    (should delete-selection-mode)
    (should repeat-mode)
    (should show-paren-mode)
    (should (= show-paren-delay 0))
    (should read-buffer-completion-ignore-case)
    (should completion-ignore-case)
    (should (eq tab-always-indent emacs-batteries-tab-always-indent))
    (should (eq tab-first-completion 'word-or-paren-or-punct))
    (should (= completion-cycle-threshold
               emacs-batteries-completion-cycle-threshold))
    (should switch-to-buffer-obey-display-actions)
    (should (eq help-window-select emacs-batteries-help-window-select))
    (should kill-do-not-save-duplicates)
    (should-not use-dialog-box)
    (should use-short-answers)
    (should (eq ring-bell-function emacs-batteries-ring-bell-function))
    (should (= save-interprogram-paste-before-kill
               emacs-batteries-save-interprogram-paste-before-kill))
    (should select-enable-clipboard)
    (should (eq interprogram-paste-function
                #'emacs-batteries--interprogram-paste))
    (should (memq #'emacs-batteries--maybe-enable-electric-pair
                  after-change-major-mode-hook))
    (should load-prefer-newer)
    (should scroll-preserve-screen-position)
    (should column-number-mode)
    (should (eq uniquify-buffer-name-style
                emacs-batteries-uniquify-buffer-name-style))
    (should isearch-lazy-count)
    (should (equal lazy-count-prefix-format "(%s/%s) "))
    (should-not lazy-count-suffix-format)
    (should (= lazy-highlight-initial-delay 0))
    (should read-file-name-completion-ignore-case)
    (should completions-detailed)
    (should (eq require-final-newline
                emacs-batteries-require-final-newline))
    (should (eq ffap-machine-p-known 'reject))
    (should-not sentence-end-double-space)
    (should set-mark-command-repeat-pop)
    (should window-resize-pixelwise)
    (should show-paren-when-point-inside-paren)
    (should show-paren-when-point-in-periphery)
    (should which-key-mode)
    (should context-menu-mode)
    (should (eq xref-show-definitions-function
                #'xref-show-definitions-completing-read))
    (should apropos-do-all)
    (should dired-dwim-target)
    (should (eq dired-recursive-copies 'always))
    (should (eq dired-recursive-deletes 'top))
    (should (eq dired-create-destination-dirs 'ask))
    (should dired-kill-when-opening-new-dired-buffer)
    (should (equal dired-listing-switches "-alh"))
    (should dired-auto-revert-buffer)
    (should (eq ediff-window-setup-function #'ediff-setup-windows-plain))
    (should (eq ediff-split-window-function #'split-window-horizontally))
    (should auto-save-no-message)
    (should auto-save-include-big-deletions)
    (should find-file-visit-truename)
    (should find-file-suppress-same-file-warnings)
    (should-not confirm-nonexistent-file-or-buffer)
    (should vc-follow-symlinks)
    (should (= bookmark-save-flag 1))
    (should (eq save-abbrevs 'silently))
    (should kill-buffer-delete-auto-save-files)
    (should mouse-yank-at-point)
    (should-not auto-window-vscroll)
    (should inhibit-compacting-font-caches)
    (should frame-resize-pixelwise)
    (should bidi-inhibit-bpa)
    (should (= scroll-conservatively emacs-batteries-scroll-conservatively))
    (should scroll-error-top-bottom)
    (should (= hscroll-margin 2))
    (should (= hscroll-step 1))
    (should (= jit-lock-defer-time 0.25))
    (should-not process-adaptive-read-buffering)
    (should-not next-line-add-newlines)
    (should-not eval-expression-print-length)
    (should-not eval-expression-print-level)
    (should (eq compilation-scroll-output 'first-error))
    (should compilation-always-kill)
    (should-not compilation-ask-about-save)
    (should gnutls-verify-error)
    (should (= gnutls-min-prime-bits 3072))
    (should (eq epg-pinentry-mode 'loopback))
    (should imenu-auto-rescan)
    (should (eq resize-mini-windows 'grow-only))
    (should comment-multi-line)
    (should comment-empty-lines)
    (should (equal truncate-string-ellipsis "\u2026"))
    (should (eq initial-major-mode emacs-batteries-initial-major-mode))
    (should-not initial-scratch-message)
    (should editorconfig-mode)
    (should (memq #'emacs-batteries--maybe-enable-display-line-numbers
                  after-change-major-mode-hook))
    (should (memq #'emacs-batteries--maybe-enable-subword
                  after-change-major-mode-hook))
    (should (memq #'executable-make-buffer-file-executable-if-script-p
                  after-save-hook))
    (should (memq #'cursor-intangible-mode minibuffer-setup-hook))
    (should (memq #'emacs-batteries--maybe-enable-completion-preview
                  after-change-major-mode-hook))
    (should (memq #'emacs-batteries--maybe-show-trailing-whitespace
                  after-change-major-mode-hook))
    (should (memq #'goto-address-prog-mode prog-mode-hook))
    (should-not blink-matching-paren)
    (when (boundp 'display-time-default-load-average)
      (should-not display-time-default-load-average))
    (should (= large-file-warning-threshold
               emacs-batteries-large-file-warning-threshold))
    (should-not eldoc-echo-area-use-multiline-p)
    (should mouse-wheel-tilt-scroll)
    (should custom-buffer-done-kill)
    (should custom-buffer-done-kill)
    (should-not use-file-dialog)
    (should backup-by-copying-when-linked)
    (should display-raw-bytes-as-hex)
    (should (eq url-privacy-level 'high))
    (should isearch-allow-scroll)
    (should (eq comint-scroll-to-bottom-on-input 'this))
    (should-not ediff-keep-variants)
    (should (equal vc-git-diff-switches '("--histogram")))
    (should (eq dired-deletion-confirmer #'y-or-n-p))
    (should comint-prompt-read-only)
    (should (= undo-limit 160000))
    (should (= undo-strong-limit 240000))
    (should (= split-width-threshold emacs-batteries-split-width-threshold))
    (should (= tramp-verbose 1))
    (should diff-refine)
    (should (memq 'search-ring savehist-additional-variables))
    (should (memq 'regexp-search-ring savehist-additional-variables))
    (should (memq 'compile-command savehist-additional-variables))
    (dolist (cmd '(narrow-to-region upcase-region downcase-region
                   narrow-to-page scroll-left dired-find-alternate-file
                   erase-buffer set-goal-column list-timers list-threads))
      (should-not (get cmd 'disabled)))
    (should-not (timerp savehist-timer))
    (should (equal savehist-file
                   (expand-file-name "savehist.eld"
                                     emacs-batteries-state-directory)))
    (should (equal recentf-save-file
                   (expand-file-name "recentf.eld"
                                     emacs-batteries-state-directory)))
    (should (equal save-place-file
                   (expand-file-name "saveplace.eld"
                                     emacs-batteries-state-directory)))))

(ert-deftest emacs-batteries-setup-configures-safe-saving ()
  (emacs-batteries-test--with-sandbox
    (emacs-batteries-setup)
    (let ((backup-directory
           (expand-file-name "backup/" emacs-batteries-state-directory))
          (autosave-directory
           (expand-file-name "auto-save/" emacs-batteries-state-directory)))
      (should make-backup-files)
      (should (eq version-control t))
      (should (eq delete-old-versions t))
      (should (= kept-new-versions emacs-batteries-kept-new-backups))
      (should (= kept-old-versions emacs-batteries-kept-old-backups))
      (should (eq backup-by-copying emacs-batteries-backup-by-copying))
      (should create-lockfiles)
      (should delete-by-moving-to-trash)
      (should (file-directory-p backup-directory))
      (should (file-directory-p autosave-directory))
      (should (equal (alist-get "." backup-directory-alist nil nil #'string=)
                     backup-directory))
      (should auto-save-default)
      (should (member `(".*" ,autosave-directory t)
                      auto-save-file-name-transforms))
      (should (string-prefix-p autosave-directory auto-save-list-file-prefix)))))

(ert-deftest emacs-batteries-setup-is-idempotent ()
  (emacs-batteries-test--with-sandbox
    (emacs-batteries-setup)
    (let ((auto-save-transforms (copy-tree auto-save-file-name-transforms))
          (major-mode-hooks (copy-tree after-change-major-mode-hook)))
      (emacs-batteries-setup)
      (should (equal auto-save-file-name-transforms auto-save-transforms))
      (should (equal after-change-major-mode-hook major-mode-hooks))
      (should-not (timerp savehist-timer)))))

(ert-deftest emacs-batteries-setup-preserves-specific-backup-rules ()
  (emacs-batteries-test--with-sandbox
    (let* ((specific-directory
            (expand-file-name "specific/" emacs-batteries-state-directory))
           (backup-directory
            (expand-file-name "backup/" emacs-batteries-state-directory))
           (backup-directory-alist
            `(("^/tmp/project/" . ,specific-directory)
              ("." . "/old-default/"))))
      (emacs-batteries-setup)
      (should (equal backup-directory-alist
                     `(("^/tmp/project/" . ,specific-directory)
                       ("." . ,backup-directory))))
      (should (equal (assoc-default "/tmp/project/file.txt"
                                    backup-directory-alist
                                    #'string-match)
                     specific-directory))
      (should (equal (assoc-default "/tmp/other/file.txt"
                                    backup-directory-alist
                                    #'string-match)
                     backup-directory)))))

(ert-deftest emacs-batteries-setup-enables-electric-pair-only-in-prog-buffers ()
  (emacs-batteries-test--with-sandbox
    (emacs-batteries-setup)
    (with-temp-buffer
      (emacs-lisp-mode)
      (should (bound-and-true-p electric-pair-mode)))
    (with-temp-buffer
      (text-mode)
      (should-not (bound-and-true-p electric-pair-mode)))))

(ert-deftest emacs-batteries-setup-respects-opt-out-settings ()
  (emacs-batteries-test--with-sandbox
    (let ((emacs-batteries-enable-recentf nil)
          (emacs-batteries-enable-auto-revert nil)
          (emacs-batteries-auto-revert-non-file-buffers nil)
          (emacs-batteries-enable-so-long nil)
          (emacs-batteries-enable-recursive-minibuffers nil)
          (emacs-batteries-enable-minibuffer-depth-indicate nil)
          (emacs-batteries-enable-minibuffer-electric-default nil)
          (emacs-batteries-enable-winner-mode nil)
          (emacs-batteries-read-extended-command-predicate nil)
          (emacs-batteries-confirm-kill-emacs nil)
          (emacs-batteries-switch-to-buffer-obey-display-actions nil)
          (emacs-batteries-help-window-select nil)
          (emacs-batteries-ring-bell-function nil)
          (emacs-batteries-enable-delete-selection nil)
          (emacs-batteries-enable-repeat-mode nil)
          (emacs-batteries-enable-show-paren nil)
          (emacs-batteries-enable-pixel-scroll-precision nil)
          (emacs-batteries-enable-electric-pair-in-prog-mode nil)
          (emacs-batteries-use-dialog-box t)
          (emacs-batteries-use-short-answers nil)
          (emacs-batteries-tab-always-indent t)
          (emacs-batteries-completion-cycle-threshold nil)
          (emacs-batteries-enable-column-number-mode nil)
          (emacs-batteries-enable-isearch-lazy-count nil)
          (emacs-batteries-enable-uniquify nil)
          (emacs-batteries-completions-detailed nil)
          (emacs-batteries-require-final-newline nil)
          (emacs-batteries-enable-which-key-mode nil)
          (emacs-batteries-enable-context-menu-mode nil)
          (emacs-batteries-dired-dwim-target nil)
          (emacs-batteries-enable-editorconfig nil)
          (emacs-batteries-enable-display-line-numbers-in-prog-mode nil)
          (emacs-batteries-enable-subword-in-prog-mode nil)
          (emacs-batteries-scroll-conservatively nil)
          (emacs-batteries-bidi-inhibit-bpa nil)
          (emacs-batteries-gnutls-verify-error nil)
          (emacs-batteries-enable-completion-preview-in-prog-mode nil)
          (emacs-batteries-enable-visual-wrap-prefix nil)
          (emacs-batteries-split-width-threshold nil)
          (emacs-batteries-enable-kill-ring-deindent nil)
          (emacs-batteries-show-trailing-whitespace-in-prog-mode nil)
          (emacs-batteries-enable-goto-address-in-prog-mode nil))
      (emacs-batteries-setup)
      (should-not recentf-mode)
      (should-not global-auto-revert-mode)
      (should-not global-auto-revert-non-file-buffers)
      (should-not global-so-long-mode)
      (should-not enable-recursive-minibuffers)
      (should-not confirm-kill-emacs)
      (should-not read-extended-command-predicate)
      (should-not switch-to-buffer-obey-display-actions)
      (should-not help-window-select)
      (should-not delete-selection-mode)
      (should-not repeat-mode)
      (should-not show-paren-mode)
      (should-not winner-mode)
      (should-not minibuffer-depth-indicate-mode)
      (should-not minibuffer-electric-default-mode)
      (should-not pixel-scroll-precision-mode)
      (should (equal use-dialog-box t))
      (should-not use-short-answers)
      (should-not ring-bell-function)
      (should (eq tab-always-indent t))
      (should-not completion-cycle-threshold)
      (should-not column-number-mode)
      (should-not isearch-lazy-count)
      (should-not completions-detailed)
      (should-not require-final-newline)
      (should-not which-key-mode)
      (should-not context-menu-mode)
      (should-not dired-dwim-target)
      (should-not editorconfig-mode)
      (should-not gnutls-verify-error)
      (should-not (memq #'emacs-batteries--maybe-enable-electric-pair
                        after-change-major-mode-hook))
      (should-not (memq #'emacs-batteries--maybe-enable-display-line-numbers
                        after-change-major-mode-hook))
      (should-not (memq #'emacs-batteries--maybe-enable-subword
                        after-change-major-mode-hook))
      (should-not (memq #'emacs-batteries--maybe-enable-completion-preview
                        after-change-major-mode-hook))
      (should-not (memq #'emacs-batteries--maybe-show-trailing-whitespace
                        after-change-major-mode-hook))
      (should-not (memq #'goto-address-prog-mode prog-mode-hook))
      (with-temp-buffer
        (emacs-lisp-mode)
        (should-not (bound-and-true-p electric-pair-mode))))))

(ert-deftest emacs-batteries-setup-configures-search-extended-defaults ()
  (emacs-batteries-test--with-sandbox
    (emacs-batteries-setup)
    (when (boundp 'xref-history-storage)
      (should (eq xref-history-storage 'xref-window-local-history)))
    (when (boundp 'find-library-include-other-files)
      (should-not find-library-include-other-files))
    (when (boundp 'isearch-wrap-pause)
      (should (eq isearch-wrap-pause 'no)))
    (when (boundp 'lazy-highlight-buffer)
      (should lazy-highlight-buffer))
    (when (boundp 'grep-use-headings)
      (should grep-use-headings))))

(ert-deftest emacs-batteries-setup-configures-dired-extended-defaults ()
  (emacs-batteries-test--with-sandbox
    (emacs-batteries-setup)
    (when (boundp 'dired-movement-style)
      (should (eq dired-movement-style 'bounded)))
    (when (boundp 'dired-vc-rename-file)
      (should dired-vc-rename-file))))

(ert-deftest emacs-batteries-setup-configures-shell-extended-defaults ()
  (emacs-batteries-test--with-sandbox
    (emacs-batteries-setup)
    (when (boundp 'eshell-history-append)
      (should eshell-history-append))
    (when (boundp 'shell-kill-buffer-on-exit)
      (should shell-kill-buffer-on-exit))))

(ert-deftest emacs-batteries-setup-configures-compilation-extended-defaults ()
  (emacs-batteries-test--with-sandbox
    (emacs-batteries-setup)
    (when (boundp 'compilation-max-output-line-length)
      (should-not compilation-max-output-line-length))))

(ert-deftest emacs-batteries-setup-configures-diff-enables-kill-ring-deindent ()
  (emacs-batteries-test--with-sandbox
    (emacs-batteries-setup)
    (when (fboundp 'global-kill-ring-deindent-mode)
      (should (bound-and-true-p global-kill-ring-deindent-mode)))))

(ert-deftest emacs-batteries-setup-configures-window-extended-defaults ()
  (emacs-batteries-test--with-sandbox
    (emacs-batteries-setup)
    (when (boundp 'help-window-keep-selected)
      (should help-window-keep-selected))
    (when (boundp 'switch-to-buffer-in-dedicated-window)
      (should (eq switch-to-buffer-in-dedicated-window 'pop)))))

(ert-deftest emacs-batteries-setup-configures-display-extended-defaults ()
  (emacs-batteries-test--with-sandbox
    (emacs-batteries-setup)
    (when (boundp 'what-cursor-show-names)
      (should what-cursor-show-names))
    (when (boundp 'completions-header-format)
      (should-not completions-header-format))
    (when (boundp 'help-enable-variable-value-editing)
      (should help-enable-variable-value-editing))
    (when (boundp 'register-use-preview)
      (should register-use-preview))
    (when (boundp 'tab-bar-show)
      (should (= tab-bar-show 1)))
    (when (boundp 'outline-minor-mode-cycle)
      (should outline-minor-mode-cycle))
    (when (boundp 'project-mode-line)
      (should project-mode-line))
    (when (boundp 'describe-bindings-outline)
      (should describe-bindings-outline))
    (when (boundp 'imenu-flatten)
      (should (eq imenu-flatten 'prefix)))
    (when (fboundp 'global-visual-wrap-prefix-mode)
      (should (bound-and-true-p global-visual-wrap-prefix-mode)))))

(ert-deftest emacs-batteries-setup-configures-performance-extended-defaults ()
  (emacs-batteries-test--with-sandbox
    (emacs-batteries-setup)
    (when (boundp 'native-compile-prune-cache)
      (should native-compile-prune-cache))
    (when (boundp 'native-comp-async-report-warnings-errors)
      (should (eq native-comp-async-report-warnings-errors 'silent)))
    (when (boundp 'global-text-scale-adjust-resizes-frames)
      (should-not global-text-scale-adjust-resizes-frames))
    (when (boundp 'x-underline-at-descent-line)
      (should x-underline-at-descent-line))
    (when (boundp 'proced-enable-color-flag)
      (should proced-enable-color-flag))))

(ert-deftest emacs-batteries-setup-configures-minibuffer-extended-defaults ()
  (emacs-batteries-test--with-sandbox
    (emacs-batteries-setup)
    (when (boundp 'read-minibuffer-restore-windows)
      (should-not read-minibuffer-restore-windows))))

(ert-deftest emacs-batteries-setup-configures-editing-extended-defaults ()
  (emacs-batteries-test--with-sandbox
    (emacs-batteries-setup)
    (when (boundp 'text-mode-ispell-word-completion)
      (should-not text-mode-ispell-word-completion))
    (when (boundp 'completions-sort)
      (should (eq completions-sort 'historical)))))

(ert-deftest emacs-batteries-setup-defers-require-heavy-functions-during-startup ()
  (emacs-batteries-test--with-sandbox
    (let ((after-init-time nil)
          (emacs-batteries-defer-setup t))
      (emacs-batteries-setup)
      ;; Deferred functions should be pending.
      (should emacs-batteries--deferred-functions)
      (should (memq #'emacs-batteries--run-deferred emacs-startup-hook))
      ;; savehist etc. should not yet be active.
      (should-not savehist-mode)
      (should-not save-place-mode)
      ;; Flush and verify.
      (emacs-batteries-test--flush-deferred)
      (should savehist-mode)
      (should save-place-mode)
      (should-not emacs-batteries--deferred-functions)
      (should-not (memq #'emacs-batteries--run-deferred emacs-startup-hook)))))

(ert-deftest emacs-batteries-setup-runs-immediately-when-defer-disabled ()
  (emacs-batteries-test--with-sandbox
    (let ((emacs-batteries-defer-setup nil))
      (emacs-batteries-setup)
      (should savehist-mode)
      (should save-place-mode)
      (should recentf-mode)
      (should global-auto-revert-mode)
      (should-not emacs-batteries--deferred-functions))))

(ert-deftest emacs-batteries-setup-enables-tty-clipboard-integration-on-xterm-like-terminals ()
  (emacs-batteries-test--with-sandbox
    (let ((original-terminal-initted
           (terminal-parameter nil 'terminal-initted))
          (original-set-selection
           (terminal-parameter nil 'xterm--set-selection))
          (original-get-selection
           (terminal-parameter nil 'xterm--get-selection))
          (process-environment
           (cl-remove-if
            (lambda (entry)
              (string-match-p
               "\\`\\(TERM_PROGRAM\\|WEZTERM_EXECUTABLE\\|WEZTERM_PANE\\)="
               entry))
            process-environment)))
      (unwind-protect
          (progn
            (set-terminal-parameter nil 'terminal-initted 'terminal-init-xterm)
            (set-terminal-parameter nil 'xterm--set-selection nil)
            (set-terminal-parameter nil 'xterm--get-selection nil)
            (emacs-batteries-setup)
            (should (memq #'emacs-batteries--enable-terminal-clipboard-integration
                          tty-setup-hook))
            (should (eq (terminal-parameter nil 'xterm--set-selection) t))
            (should (eq (terminal-parameter nil 'xterm--get-selection) t)))
        (set-terminal-parameter nil 'terminal-initted original-terminal-initted)
        (set-terminal-parameter nil 'xterm--set-selection original-set-selection)
        (set-terminal-parameter nil 'xterm--get-selection original-get-selection)))))

(ert-deftest emacs-batteries-setup-can-disable-tty-clipboard-paste ()
  (emacs-batteries-test--with-sandbox
    (let ((original-terminal-initted
           (terminal-parameter nil 'terminal-initted))
          (original-set-selection
           (terminal-parameter nil 'xterm--set-selection))
          (original-get-selection
           (terminal-parameter nil 'xterm--get-selection))
          (process-environment
           (cl-remove-if
            (lambda (entry)
              (string-match-p
               "\\`\\(TERM_PROGRAM\\|WEZTERM_EXECUTABLE\\|WEZTERM_PANE\\)="
               entry))
            process-environment))
          (emacs-batteries-enable-terminal-clipboard-paste nil))
      (unwind-protect
          (progn
            (set-terminal-parameter nil 'terminal-initted 'terminal-init-xterm)
            (set-terminal-parameter nil 'xterm--set-selection nil)
            (set-terminal-parameter nil 'xterm--get-selection nil)
            (emacs-batteries-setup)
            (should (eq (terminal-parameter nil 'xterm--set-selection) t))
            (should-not (terminal-parameter nil 'xterm--get-selection)))
        (set-terminal-parameter nil 'terminal-initted original-terminal-initted)
        (set-terminal-parameter nil 'xterm--set-selection original-set-selection)
        (set-terminal-parameter nil 'xterm--get-selection original-get-selection)))))

(ert-deftest emacs-batteries-setup-skips-tty-clipboard-query-on-wezterm ()
  (emacs-batteries-test--with-sandbox
    (let ((original-terminal-initted
           (terminal-parameter nil 'terminal-initted))
          (original-set-selection
           (terminal-parameter nil 'xterm--set-selection))
          (original-get-selection
           (terminal-parameter nil 'xterm--get-selection))
          (process-environment
           (cons "TERM_PROGRAM=WezTerm"
                 (cl-remove-if
                  (lambda (entry)
                    (string-match-p
                     "\\`\\(TERM_PROGRAM\\|WEZTERM_EXECUTABLE\\|WEZTERM_PANE\\)="
                     entry))
                  process-environment))))
      (unwind-protect
          (progn
            (set-terminal-parameter nil 'terminal-initted 'terminal-init-xterm)
            (set-terminal-parameter nil 'xterm--set-selection nil)
            (set-terminal-parameter nil 'xterm--get-selection nil)
            (emacs-batteries-setup)
            (should (eq (terminal-parameter nil 'xterm--set-selection) t))
            (should-not (terminal-parameter nil 'xterm--get-selection)))
        (set-terminal-parameter nil 'terminal-initted original-terminal-initted)
        (set-terminal-parameter nil 'xterm--set-selection original-set-selection)
        (set-terminal-parameter nil 'xterm--get-selection original-get-selection)))))

(ert-deftest emacs-batteries-setup-reenables-clipboard-integration ()
  (emacs-batteries-test--with-sandbox
    (let ((select-enable-clipboard nil))
      (emacs-batteries-setup)
      (should select-enable-clipboard))))

(ert-deftest emacs-batteries-setup-wraps-interprogram-paste-on-macos ()
  (emacs-batteries-test--with-sandbox
    (let ((system-type 'darwin)
          (interprogram-paste-function #'gui-selection-value))
      (emacs-batteries-setup)
      (should (eq interprogram-paste-function
                  #'emacs-batteries--interprogram-paste))
      (should (eq emacs-batteries--interprogram-paste-base-function
                  #'gui-selection-value)))))

(ert-deftest emacs-batteries-setup-restores-default-interprogram-paste-function ()
  (emacs-batteries-test--with-sandbox
    (let ((interprogram-paste-function nil))
      (emacs-batteries-setup)
      (should (eq interprogram-paste-function
                  #'emacs-batteries--interprogram-paste))
      (should (eq emacs-batteries--interprogram-paste-base-function
                  #'gui-selection-value))
      (cl-letf (((symbol-function 'gui-selection-value)
                 (lambda ()
                   "from clipboard")))
        (should (equal (funcall interprogram-paste-function)
                       "from clipboard"))))))

(ert-deftest emacs-batteries-setup-wraps-interprogram-cut-function ()
  (emacs-batteries-test--with-sandbox
    (let ((interprogram-cut-function #'gui-select-text))
      (emacs-batteries-setup)
      (should (eq interprogram-cut-function
                  #'emacs-batteries--interprogram-cut))
      (should (eq emacs-batteries--interprogram-cut-base-function
                  #'gui-select-text)))))

(ert-deftest emacs-batteries-interprogram-cut-falls-back-to-pbcopy-on-macos-tty-without-osc52-copy ()
  (emacs-batteries-test--with-sandbox
    (let ((system-type 'darwin)
          (window-system nil)
          (interprogram-cut-function #'gui-select-text))
      (emacs-batteries-setup)
      (cl-letf (((symbol-function 'gui-select-text)
                 (lambda (_text)
                   (ert-fail "gui-select-text should not run without OSC 52 copy support")))
                ((symbol-function 'emacs-batteries--macos-terminal-clipboard-copy-with-pbcopy)
                 (lambda (text)
                   (should (equal text "from emacs"))
                   t)))
        (funcall interprogram-cut-function "from emacs")))))

(ert-deftest emacs-batteries-interprogram-cut-uses-both-pbcopy-and-osc52-on-macos-tty ()
  (emacs-batteries-test--with-sandbox
    (let ((system-type 'darwin)
          (window-system nil)
          (interprogram-cut-function #'gui-select-text)
          (osc52-calls 0)
          (pbcopy-calls 0)
          (original-terminal-initted
           (terminal-parameter nil 'terminal-initted))
          (original-set-selection
           (terminal-parameter nil 'xterm--set-selection)))
      (unwind-protect
          (progn
            (set-terminal-parameter nil 'terminal-initted 'terminal-init-xterm)
            (set-terminal-parameter nil 'xterm--set-selection nil)
            (emacs-batteries-setup)
            (cl-letf (((symbol-function 'send-string-to-terminal)
                       (lambda (str)
                         (when (string-prefix-p "\e]52;" str)
                           (setq osc52-calls (1+ osc52-calls)))))
                      ((symbol-function 'emacs-batteries--macos-terminal-clipboard-copy-with-pbcopy)
                       (lambda (text)
                         (should (equal text "from emacs"))
                         (setq pbcopy-calls (1+ pbcopy-calls))
                         t)))
              (funcall interprogram-cut-function "from emacs")
              (should (= osc52-calls 1))
              (should (= pbcopy-calls 1))))
        (set-terminal-parameter nil 'terminal-initted original-terminal-initted)
        (set-terminal-parameter nil 'xterm--set-selection original-set-selection)))))

(ert-deftest emacs-batteries-macos-terminal-clipboard-copy-with-pbcopy-sends-eof-and-waits-for-exit ()
  (emacs-batteries-test--with-sandbox
    (let ((proc 'pbcopy-process)
          (start-process-seen nil)
          (coding-system-seen nil)
          (sent-text nil)
          (sent-eof nil)
          (accept-calls 0)
          (live-states '(t nil)))
      (cl-letf (((symbol-function 'executable-find)
                 (lambda (command)
                   (and (equal command "pbcopy")
                        "/usr/bin/pbcopy")))
                ((symbol-function 'start-process)
                 (lambda (name buffer program &rest _args)
                   (should (equal name "emacs-batteries-pbcopy"))
                   (should-not buffer)
                   (should (equal program "/usr/bin/pbcopy"))
                   (should (null process-connection-type))
                   (setq start-process-seen t)
                   proc))
                ((symbol-function 'set-process-coding-system)
                 (lambda (process input output)
                   (should (eq process proc))
                   (setq coding-system-seen (list input output))))
                ((symbol-function 'process-send-string)
                 (lambda (process text)
                   (should (eq process proc))
                   (setq sent-text text)))
                ((symbol-function 'process-send-eof)
                 (lambda (process)
                   (should (eq process proc))
                   (setq sent-eof t)))
                ((symbol-function 'process-live-p)
                 (lambda (process)
                   (should (eq process proc))
                   (prog1 (car live-states)
                     (setq live-states (cdr live-states)))))
                ((symbol-function 'accept-process-output)
                 (lambda (process timeout &optional _millisec)
                   (should (eq process proc))
                   (should (= timeout 0.01))
                   (setq accept-calls (1+ accept-calls))
                   t))
                ((symbol-function 'process-status)
                 (lambda (process)
                   (should (eq process proc))
                   'exit))
                ((symbol-function 'process-exit-status)
                 (lambda (process)
                   (should (eq process proc))
                   0)))
        (should (emacs-batteries--macos-terminal-clipboard-copy-with-pbcopy
                 "from emacs"))
        (should start-process-seen)
        (should (equal coding-system-seen '(utf-8-unix utf-8-unix)))
        (should (equal sent-text "from emacs"))
        (should sent-eof)
        (should (= accept-calls 1))))))

(ert-deftest emacs-batteries-interprogram-paste-falls-back-to-finder-files ()
  (emacs-batteries-test--with-sandbox
    (let ((system-type 'darwin)
          (window-system 'ns)
          (interprogram-paste-function
           (lambda ()
             nil)))
      (emacs-batteries-setup)
      (cl-letf (((symbol-function 'gui-get-selection)
                 (lambda (_selection target)
                   (pcase target
                     ('text/plain
                      "file:///tmp/hello%20world\nfile:///tmp/second")
                     (_ nil)))))
        (should (equal (funcall interprogram-paste-function)
                       "/tmp/hello world\n/tmp/second"))
        (should-not (funcall interprogram-paste-function))))))

(ert-deftest emacs-batteries-interprogram-paste-falls-back-to-pbpaste-on-macos-tty ()
  (emacs-batteries-test--with-sandbox
    (let ((system-type 'darwin)
          (window-system nil)
          (interprogram-paste-function
           (lambda ()
             nil)))
      (emacs-batteries-setup)
      (cl-letf (((symbol-function 'executable-find)
                 (lambda (command)
                   (and (equal command "pbpaste")
                        "/usr/bin/pbpaste")))
                ((symbol-function 'process-file)
                 (lambda (program infile buffer display &rest args)
                   (ignore infile display args)
                   (should (equal program "/usr/bin/pbpaste"))
                   (princ "from pbpaste"
                          (if (eq buffer t) (current-buffer) buffer))
                   0)))
        (should (equal (funcall interprogram-paste-function)
                       "from pbpaste"))))))

(ert-deftest emacs-batteries-interprogram-paste-does-not-let-stale-pbpaste-beat-recent-kill ()
  (emacs-batteries-test--with-sandbox
    (let ((system-type 'darwin)
          (window-system nil)
          (kill-ring nil)
          (kill-ring-yank-pointer nil)
          (macos-clipboard "from macos")
          (interprogram-cut-function
           (lambda (_text)
             ;; Simulate a broken OSC 52 copy path that leaves macOS clipboard unchanged.
             nil))
          (interprogram-paste-function
           (lambda ()
             nil)))
      (emacs-batteries-setup)
      (cl-letf (((symbol-function 'executable-find)
                 (lambda (command)
                   (and (equal command "pbpaste")
                        "/usr/bin/pbpaste")))
                ((symbol-function 'process-file)
                 (lambda (program infile buffer display &rest args)
                   (ignore infile display args)
                   (should (equal program "/usr/bin/pbpaste"))
                   (princ macos-clipboard
                          (if (eq buffer t) (current-buffer) buffer))
                   0)))
        (kill-new "from emacs")
        (should (equal (current-kill 0) "from emacs"))
        (setq macos-clipboard "from wezterm")
        (should (equal (current-kill 0) "from wezterm"))))))

(ert-deftest emacs-batteries-interprogram-paste-respects-terminal-clipboard-paste-opt-out-on-macos-tty ()
  (emacs-batteries-test--with-sandbox
    (let ((system-type 'darwin)
          (window-system nil)
          (emacs-batteries-enable-terminal-clipboard-paste nil)
          (interprogram-paste-function
           (lambda ()
             nil)))
      (emacs-batteries-setup)
      (cl-letf (((symbol-function 'executable-find)
                 (lambda (_command)
                   (ert-fail "pbpaste should not be queried when terminal clipboard paste is disabled"))))
        (should-not (funcall interprogram-paste-function))))))

(ert-deftest emacs-batteries-interprogram-paste-prefers-base-function ()
  (emacs-batteries-test--with-sandbox
    (let ((system-type 'darwin)
          (window-system 'ns)
          (interprogram-paste-function
           (lambda ()
             "plain text")))
      (emacs-batteries-setup)
      (cl-letf (((symbol-function 'gui-get-selection)
                 (lambda (&rest _args)
                   "file:///tmp/ignored")))
        (should (equal (funcall interprogram-paste-function)
                       "plain text"))))))

(ert-deftest emacs-batteries-setup-applies-darwin-utf-8-profile ()
  (emacs-batteries-test--with-sandbox
    (let ((system-type 'darwin)
          (emacs-batteries-coding-system 'utf-8)
          (file-name-coding-system nil)
          (default-file-name-coding-system nil)
          (selection-coding-system nil)
          (locale-coding-system 'japanese-shift-jis)
          (buffer-file-coding-system 'japanese-shift-jis-unix)
          (default-process-coding-system
           '(japanese-shift-jis-unix . japanese-shift-jis-unix)))
      (emacs-batteries-setup)
      (should (eq (default-value 'buffer-file-coding-system) 'utf-8-unix))
      (should (equal default-process-coding-system
                     '(utf-8-unix . utf-8-unix)))
      (should (eq file-name-coding-system 'utf-8-hfs-unix))
      (should (eq default-file-name-coding-system 'utf-8-hfs-unix))
      (should (eq selection-coding-system 'utf-8)))))

(ert-deftest emacs-batteries-setup-temporarily-relaxes-gc-during-startup ()
  (emacs-batteries-test--with-sandbox
    (let ((after-init-time nil)
          (gc-cons-threshold 800000)
          (gc-cons-percentage 0.1))
      (emacs-batteries-setup)
      (should (= gc-cons-threshold
                 emacs-batteries-startup-gc-cons-threshold))
      (should (eq emacs-batteries--saved-gc-cons-threshold 800000))
      (should (= emacs-batteries--saved-gc-cons-percentage 0.1))
      (should (memq #'emacs-batteries--restore-startup-gc emacs-startup-hook))
      (emacs-batteries--restore-startup-gc)
      (should (= gc-cons-threshold 800000))
      (should (= gc-cons-percentage 0.1))
      (should-not emacs-batteries--saved-gc-cons-threshold)
      (should-not emacs-batteries--saved-gc-cons-percentage)
      (should-not (memq #'emacs-batteries--restore-startup-gc
                        emacs-startup-hook)))))

(ert-deftest emacs-batteries-early-init-disables-package.el-auto-startup ()
  (emacs-batteries-test--with-sandbox
    (let ((after-init-time nil)
          (package-enable-at-startup t)
          (inhibit-default-init nil)
          (inhibit-startup-screen nil)
          (default-frame-alist
           '((menu-bar-lines . 1)
             (tool-bar-lines . 1)
             (vertical-scroll-bars . left)))
          (initial-frame-alist
           '((menu-bar-lines . 1)
             (tool-bar-lines . 1)
             (vertical-scroll-bars . right)))
          (frame-inhibit-implied-resize nil)
          (read-process-output-max 65536)
          (file-name-handler-alist
           '(("\\.gz\\'" . jka-compr-handler)
             ("\\`/[^/|:]+:" . tramp-autoload-file-name-handler)
             ("\\`/:" . file-name-non-special)))
          (gc-cons-threshold 800000)
          (gc-cons-percentage 0.1)
          (emacs-startup-hook nil)
          (emacs-batteries--saved-gc-cons-threshold nil)
          (emacs-batteries--saved-gc-cons-percentage nil)
          (emacs-batteries--saved-file-name-handler-alist nil))
      (load (emacs-batteries-test--fixture-path "emacs-batteries-early-init.el")
            nil 'nomessage)
      (should-not package-enable-at-startup)
      (should inhibit-default-init)
      (should inhibit-startup-screen)
      (should (equal (cdr (assq 'menu-bar-lines default-frame-alist)) 0))
      (should (equal (cdr (assq 'tool-bar-lines default-frame-alist)) 0))
      (should (assq 'vertical-scroll-bars default-frame-alist))
      (should-not (cdr (assq 'vertical-scroll-bars default-frame-alist)))
      (should (assq 'horizontal-scroll-bars default-frame-alist))
      (should-not (cdr (assq 'horizontal-scroll-bars default-frame-alist)))
      (should (equal (cdr (assq 'menu-bar-lines initial-frame-alist)) 0))
      (should (equal (cdr (assq 'tool-bar-lines initial-frame-alist)) 0))
      (should (assq 'vertical-scroll-bars initial-frame-alist))
      (should-not (cdr (assq 'vertical-scroll-bars initial-frame-alist)))
      (should frame-inhibit-implied-resize)
      (should (= read-process-output-max 1048576))
      (should (equal file-name-handler-alist
                     '(("\\.gz\\'" . jka-compr-handler)
                       ("\\`/:" . file-name-non-special))))
      (should (equal emacs-batteries--saved-file-name-handler-alist
                     '(("\\.gz\\'" . jka-compr-handler)
                       ("\\`/[^/|:]+:" . tramp-autoload-file-name-handler)
                       ("\\`/:" . file-name-non-special))))
      (should (= gc-cons-threshold emacs-batteries-startup-gc-cons-threshold))
      (should (memq #'emacs-batteries--restore-startup-gc emacs-startup-hook))
      (should (memq #'emacs-batteries--restore-startup-file-name-handlers
                    emacs-startup-hook))
      (emacs-batteries--restore-startup-gc)
      (emacs-batteries--restore-startup-file-name-handlers)
      (should (= gc-cons-threshold 800000))
      (should (= gc-cons-percentage 0.1))
      (should (equal file-name-handler-alist
                     '(("\\.gz\\'" . jka-compr-handler)
                       ("\\`/[^/|:]+:" . tramp-autoload-file-name-handler)
                       ("\\`/:" . file-name-non-special)))))))

(ert-deftest emacs-batteries-bootstrap-loads-cached-helper-without-network ()
  (emacs-batteries-test--with-sandbox
    (let* ((cache-file (expand-file-name "bootstrap/helper.el"
                                         emacs-batteries-state-directory))
           (helper-loaded nil))
      (make-directory (file-name-directory cache-file) t)
      (with-temp-file cache-file
        (insert "(setq helper-loaded 'cached)\n"))
      (let ((emacs-batteries-bootstrap-cache-file cache-file)
            (emacs-batteries-bootstrap-refresh-interval nil)
            (emacs-batteries-bootstrap-checksum nil)
            (emacs-batteries-bootstrap-remote-url "https://example.invalid/helper.el"))
        (cl-letf (((symbol-function 'url-copy-file)
                   (lambda (&rest _args)
                     (error "network access should not happen"))))
          (load (emacs-batteries-test--fixture-path "bootstrap/early-init.el")
                nil 'nomessage)
          (should (eq helper-loaded 'cached)))))))

(ert-deftest emacs-batteries-bootstrap-loads-in-clean-process ()
  (let* ((temp-home (make-temp-file "emacs-batteries-home-" t))
         (cache-file
          (expand-file-name ".emacs.d/bootstrap/emacs-batteries-early-init.el"
                            temp-home))
         (bootstrap-file
          (emacs-batteries-test--fixture-path "bootstrap/early-init.el")))
    (unwind-protect
        (progn
          (make-directory (file-name-directory cache-file) t)
          (with-temp-file cache-file
            (insert "(setq helper-loaded 'cached-from-subprocess)\n"))
          (let* ((process-environment
                  (cons (concat "HOME=" temp-home) process-environment))
                 (default-directory
                  (file-name-directory bootstrap-file))
                 (result
                  (emacs-batteries-test--call-emacs
                   "-Q" "--batch"
                   "-l" bootstrap-file
                   "--eval" "(prin1 helper-loaded)")))
            (should (equal (car result) 0))
            (should (string-match-p "cached-from-subprocess" (cdr result)))))
      (delete-directory temp-home t))))

(ert-deftest emacs-batteries-bootstrap-verifies-checksum-on-download ()
  (emacs-batteries-test--with-sandbox
    (let* ((cache-file (expand-file-name "bootstrap/helper.el"
                                         emacs-batteries-state-directory))
           (source-file (expand-file-name "bootstrap/source.el"
                                          emacs-batteries-state-directory))
           (helper-loaded nil))
      (make-directory (file-name-directory source-file) t)
      (with-temp-file source-file
        (insert "(setq helper-loaded 'downloaded)\n"))
      (let ((emacs-batteries-bootstrap-cache-file cache-file)
            (emacs-batteries-bootstrap-refresh-interval nil)
            (byte-compile-current-file t)
            (emacs-batteries-bootstrap-checksum "pending")
            (emacs-batteries-bootstrap-checksum-algorithm 'sha256)
            (emacs-batteries-bootstrap-remote-url
             "https://example.invalid/helper.el"))
        (load (emacs-batteries-test--fixture-path "bootstrap/early-init.el")
              nil 'nomessage)
        (cl-letf (((symbol-function 'emacs-batteries-bootstrap--download-into)
                   (lambda (destination)
                     (copy-file source-file destination t)
                     (setq emacs-batteries-bootstrap-checksum
                           (secure-hash
                            emacs-batteries-bootstrap-checksum-algorithm
                            destination)))))
          (emacs-batteries-bootstrap-load-early-init))
        (should (file-exists-p cache-file))
        (should (eq helper-loaded 'downloaded))))))

;;; emacs-batteries-test.el ends here
